More Idiomatic Use of CMake
This commit makes sure that pthreads will be linked by CMake in the
idiomatic way (sse https://stackoverflow.com/a/29871891 as reference).
Also the linking options won't be set via CXX flags because this caused
lead to weird effects on some Linux distros (undefined reference to
`hci_get_route' on my system). See the CMake documenation:
https://cmake.org/cmake/help/latest/command/target_link_libraries.html

Finally, this commit also makes sure that build artifacts won't show up
in Git commands in the idiomatic way.